import {NextRequest,NextResponse} from 'next/server';
import {verifiedFamilyEmail} from '@/lib/cloudflare-family-access';
import {requireCalendarSyncRouteAuth} from '@/lib/calendar-sync-auth';
import {approvalState,consumeApproval,createApproval,decideApproval,listPendingApprovals,type ApprovalChoice,type DashboardApproval} from '@/lib/family-mission/approval-store';
export const dynamic='force-dynamic';
const reply=(data:any,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
const choices:ApprovalChoice[]=['once','session','always','deny'];
async function service(req:NextRequest){const auth=await requireCalendarSyncRouteAuth(req);return auth.authorized&&auth.kind==='service';}
async function parent(req:NextRequest){const email=await verifiedFamilyEmail(req.headers.get('cf-access-jwt-assertion'));if(!email)return null;return email.includes('cris')||email.includes('lacorte')?'Cris':'Dani';}
function validRequest(raw:any):raw is DashboardApproval{return raw&&typeof raw.id==='string'&&/^[a-f0-9]{32}$/.test(raw.id)&&typeof raw.digest==='string'&&/^[a-f0-9]{64}$/.test(raw.digest)&&typeof raw.command==='string'&&raw.command.length<=6000&&typeof raw.description==='string'&&raw.description.length<=2000&&Array.isArray(raw.allowedChoices)&&raw.allowedChoices.length>0&&raw.allowedChoices.every((x:any)=>choices.includes(x))&&typeof raw.createdAt==='string'&&typeof raw.expiresAt==='string';}
export async function GET(req:NextRequest){try{if(req.nextUrl.searchParams.get('worker')==='1'){if(!await service(req))return reply({error:'Unauthorized'},401);const id=req.nextUrl.searchParams.get('id')||'';return reply({approval:await approvalState(id)});}if(!await parent(req))return reply({error:'Unauthorized'},401);return reply({approvals:await listPendingApprovals()});}catch{return reply({error:'No se pudieron cargar las aprobaciones.'},503);}}
export async function POST(req:NextRequest){try{if(req.nextUrl.searchParams.get('worker')==='1'){if(!await service(req))return reply({error:'Unauthorized'},401);const body=await req.json();if(body.action==='create'&&validRequest(body.approval)){await createApproval(body.approval);return reply({ok:true});}if(body.action==='consume'&&typeof body.id==='string'){await consumeApproval(body.id);return reply({ok:true});}return reply({error:'Datos no válidos.'},400);}if(req.headers.get('origin')!==new URL(req.url).origin)return reply({error:'Unauthorized'},403);const person=await parent(req);if(!person)return reply({error:'Unauthorized'},401);const body=await req.json();if(typeof body.id!=='string'||!choices.includes(body.choice))return reply({error:'Datos no válidos.'},400);return reply({approval:await decideApproval(body.id,body.choice,person)});}catch(error){return reply({error:error instanceof Error&&error.message==='EXPIRED'?'La aprobación ha caducado.':'No se pudo guardar la decisión.'},409);}}
