// Generated by the OpenNext build.
// @ts-ignore
import handler from './.open-next/worker.js';
// @ts-ignore
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js';
export default {
    fetch: handler.fetch,
    async scheduled(_event: unknown, env: any, ctx: any) {
        if (!env.CALENDAR_SYNC_CRON_SECRET) throw new Error('Calendar sync authorization is not configured');
        const response = await handler.fetch(new Request('https://family-organizer.internal/api/calendar-sync/google/run', {
            method: 'POST', headers: { 'x-calendar-sync-secret': env.CALENDAR_SYNC_CRON_SECRET },
        }), env, ctx);
        if (!response.ok && response.status !== 409) throw new Error('Scheduled calendar sync failed: ' + response.status);
    },
};
