import {describe,it,expect,vi,beforeEach} from 'vitest';
import {NextRequest} from 'next/server';
import {validatePlace,validateLink,locationCards,personForEmail,placeDate} from '@/lib/family-mission/location-model';
vi.mock('@/lib/family-mission/tasks-route',()=>({taskActor:vi.fn()}));
vi.mock('@/lib/family-mission/location-store',()=>({listLocations:vi.fn(),writeLocation:vi.fn(),deleteLocation:vi.fn()}));
import {taskActor} from '@/lib/family-mission/tasks-route';
import {listLocations,writeLocation,deleteLocation} from '@/lib/family-mission/location-store';
import {GET,POST,DELETE} from '@/app/api/family/locations/route';
const place={id:'p',revision:1,name:'Tienda',latitude:40,longitude:2,radius:150,person:'Dani' as const,timezone:'Europe/Madrid'};
const link={id:'r',revision:1,placeId:'p',person:'Dani' as const,target:{kind:'task' as const,id:'t',listId:'l'},mode:'arrival' as const,recurring:false,expires:'2026-10-05',enabled:false};
const req=(body:any,method='POST')=>new NextRequest('https://apalas.apaniel.dev/api/family/locations',{method,headers:{origin:'https://apalas.apaniel.dev','Content-Type':'application/json'},body:JSON.stringify(body)});
beforeEach(()=>{vi.mocked(taskActor).mockResolvedValue('dapamar90@gmail.com');vi.mocked(listLocations).mockResolvedValue({places:[place],links:[link],attention:[]});vi.mocked(writeLocation).mockResolvedValue(place);});
describe('location validation and pure cards',()=>{
 it('bounds coordinates, radius, timezone and real dates',()=>{expect(validatePlace(place).name).toBe('Tienda');for(const patch of [{latitude:NaN},{longitude:181},{radius:0},{timezone:'garbage'},{person:'Saida'}])expect(()=>validatePlace({...place,...patch})).toThrow();expect(()=>validateLink({...link,expires:'2026-02-30'})).toThrow();expect(()=>validateLink({...link,target:{kind:'task',id:'t'}})).toThrow();});
 it('uses exact canonical identity and never infers completion or a fix',()=>{const record={id:'t',kind:'task',title:'Comprar',status:'open',googleTaskListId:'l'};expect(locationCards([place],[link],[record],Date.parse('2026-10-05T12:00:00Z'))[0].status).toBe('Aviso desactivado');for(const r of [{...record,status:'done'},{...record,googleTaskListId:'other'}])expect(locationCards([place],[link],[r],Date.parse('2026-10-05T12:00:00Z'))).toEqual([]);expect(locationCards([place],[link],[record],Date.parse('2026-10-06T12:00:00Z'))).toEqual([]);});
 it('expires at each place midnight from one instant',()=>{const record={id:'t',kind:'task',title:'Comprar',status:'open',googleTaskListId:'l'};const instant=Date.parse('2026-10-05T22:30:00Z');expect(locationCards([{...place,timezone:'America/New_York'}],[link],[record],instant)).toHaveLength(1);expect(locationCards([{...place,timezone:'Asia/Tokyo'}],[link],[record],instant)).toHaveLength(0);expect(placeDate('America/New_York',instant)).toBe('2026-10-05');expect(placeDate('Asia/Tokyo',instant)).toBe('2026-10-06');expect(locationCards([{...place,timezone:'America/New_York'}],[link],[record],Date.parse('2026-10-06T04:01:00Z'))).toHaveLength(0);expect(locationCards([{...place,timezone:'Asia/Tokyo'}],[link],[record],Date.parse('2026-10-05T14:59:00Z'))).toHaveLength(1);expect(()=>personForEmail('new-parent@example.com')).toThrow();});
 it('derives ownership from verified email',()=>{expect(personForEmail('dapamar90@gmail.com')).toBe('Dani');expect(personForEmail('lacorte.cristina@gmail.com')).toBe('Cris');});
});
describe('authenticated private adjunct API',()=>{
 it('rejects anonymous access and service writes',async()=>{vi.mocked(taskActor).mockResolvedValue(null);expect((await GET(req({},'POST'))).status).toBe(401);expect((await POST(req({kind:'place',...place}))).status).toBe(401);vi.mocked(taskActor).mockResolvedValue('service');expect((await POST(req({kind:'place',...place}))).status).toBe(403);expect(writeLocation).not.toHaveBeenCalled();});
 it('scopes browser reads and permits existing scoped service metadata reads',async()=>{expect((await GET(req({}))).status).toBe(200);expect(listLocations).toHaveBeenCalledWith('Dani');vi.mocked(taskActor).mockResolvedValue('service');await GET(req({}));expect(listLocations).toHaveBeenCalledWith(null);});
 it('rejects cross-person ownership and unconfirmed enable',async()=>{expect((await POST(req({kind:'place',...place,person:'Cris'}))).status).toBe(403);expect((await POST(req({kind:'link',...link,enabled:true}))).status).toBe(400);expect(writeLocation).not.toHaveBeenCalled();});
 it('creates disabled rule and derives confirmation server-side',async()=>{expect((await POST(req({kind:'link',...link,id:undefined,revision:undefined}))).status).toBe(201);expect(writeLocation).toHaveBeenCalledWith('link','Dani',expect.objectContaining({enabled:false}),undefined,undefined);await POST(req({kind:'link',...link,enabled:true,confirm:true,confirmedAt:'fake'}));expect(writeLocation).toHaveBeenLastCalledWith('link','Dani',expect.objectContaining({enabled:true,confirmedAt:expect.stringMatching(/^\d{4}-/)}),'r',1);});
 it('checks revisions and gives sanitized conflict errors',async()=>{expect((await DELETE(req({kind:'place',id:'p',revision:0},'DELETE'))).status).toBe(400);vi.mocked(deleteLocation).mockRejectedValue(new Error('CONFLICT'));expect((await DELETE(req({kind:'place',id:'p',revision:1},'DELETE'))).status).toBe(409);vi.mocked(writeLocation).mockRejectedValue(new Error('SQL secret detail'));const r=await POST(req({kind:'place',...place}));expect(r.status).toBe(503);expect(JSON.stringify(await r.json())).not.toContain('SQL');});
});
