// Google Tasks replaces the former D1 task/recurrence/audit persistence contract.
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {NextRequest} from 'next/server';
import {getCloudflareContext} from '@opennextjs/cloudflare';
import {requireCalendarSyncRouteAuth} from '@/lib/calendar-sync-auth';
import {verifiedFamilyEmail} from '@/lib/cloudflare-family-access';
import {GET,POST,DELETE} from '@/app/api/family/records/route';
import {POST as relayPOST} from '@/app/api/family/tasks/relay/route';
import {POST as flattenPOST} from '@/app/api/family/records/flatten/route';
import {readRecords,saveRecord,removeRecord} from '@/lib/family-mission/store';
import {readCompletionDigest} from '@/lib/family-mission/completion-digest-store';
import {enqueueTask,workerRelay,taskSnapshot,getTaskOperation,assertFresh} from '@/lib/family-mission/tasks-relay';
vi.mock('server-only',()=>({}));
vi.mock('@opennextjs/cloudflare',()=>({getCloudflareContext:vi.fn()}));
vi.mock('@/lib/calendar-sync-auth',()=>({requireCalendarSyncRouteAuth:vi.fn()}));
vi.mock('@/lib/cloudflare-family-access',()=>({verifiedFamilyEmail:vi.fn()}));
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite');
let sqlite:any;let beforeBatch:(()=>void)|undefined;
const task={kind:'task',id:'google-id',revision:101,title:'Disposable',date:'2026-10-01',time:'',notes:'',owner:'Familia',category:'family',reminderDays:0,status:'open',recurrence:'none',checklist:[],store:'google-tasks'};
const draft={...task,id:'',revision:0};
beforeEach(async()=>{
 beforeBatch=undefined;sqlite=new DatabaseSync(':memory:');
 for(const migration of ['0001_family_mission.sql','0006_completion_provenance.sql','0008_google_tasks_relay.sql','0009_google_tasks_fences.sql'])sqlite.exec(readFileSync(new URL('../../migrations/'+migration,import.meta.url),'utf8'));
 const db={prepare(sql:string){const statement=sqlite.prepare(sql);let args:any[]=[];const bound={bind(...values:any[]){args=values;return bound;},async first(){return statement.get(...args)??null;},async all(){return {results:statement.all(...args)};},async run(){return {meta:{changes:statement.run(...args).changes}};}};return bound;},async batch(statements:any[]){beforeBatch?.();beforeBatch=undefined;sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 vi.mocked(getCloudflareContext).mockResolvedValue({env:{FAMILY_DB:db}} as any);
 vi.mocked(requireCalendarSyncRouteAuth).mockResolvedValue({authorized:true,kind:'service'} as any);
 vi.mocked(verifiedFamilyEmail).mockResolvedValue('apavicio@gmail.com');
 await publish({records:[task]});
});
afterEach(()=>sqlite.close());
const req=(method:string,body:any,path='/api/family/records',headers={})=>new NextRequest('https://dashboard.test'+path,{method,headers,body:JSON.stringify(body)});
async function publish(body:any){const {generation}=await workerRelay({action:'snapshot-start'});if(generation===null)return {ok:false};return workerRelay({action:'snapshot',generation,...body});}
async function claim(){return (await workerRelay({action:'claim'})).command;}
async function begin(c:any){return workerRelay({action:'begin',id:c.id,leaseToken:c.leaseToken});}
async function finish(c:any,state='done',records=[task],result={record:task}){return workerRelay({action:'finish',id:c.id,leaseToken:c.leaseToken,state,records,result});}
it('fails closed for absent, expired and future mirrors',async()=>{assertFresh(Date.now());expect(()=>assertFresh(0)).toThrow();expect(()=>assertFresh(Date.now()+6000)).toThrow();sqlite.exec('DELETE FROM google_tasks_mirror');await expect(taskSnapshot()).rejects.toThrow();expect((await GET(new NextRequest('https://dashboard.test/api/family/records'))).status).toBe(200);});
it('reads Google tasks and preserves non-task D1 records while excluding stale tasks',async()=>{
 for(const [id,kind] of [['stale','task'],['meal','meal']])sqlite.prepare('INSERT INTO family_records(id,kind,data,created_at,updated_at) VALUES(?,?,?,?,?)').run(id,kind,JSON.stringify({kind,title:id}),'now','now');
 expect((await readRecords()).map(r=>r.id)).toEqual(['meal','google-id']);
 const body=await (await GET(new NextRequest('https://dashboard.test/api/family/records'))).json();expect(body).toMatchObject({taskStore:'google-tasks',taskMirror:true});
 await expect(saveRecord({...draft,sourceKey:'old'})).rejects.toThrow('Google');await expect(removeRecord('stale',1)).rejects.toThrow('Google');
});
it('rejects unauthorized read, write, delete and worker requests',async()=>{vi.mocked(requireCalendarSyncRouteAuth).mockResolvedValue({authorized:false} as any);expect((await GET(new NextRequest('https://dashboard.test/api/family/records'))).status).toBe(401);expect((await POST(req('POST',draft))).status).toBe(401);expect((await DELETE(req('DELETE',task))).status).toBe(401);expect((await relayPOST(req('POST',{action:'claim'},'/api/family/tasks/relay'))).status).toBe(401);});
it('worker route rejects parent sessions and derives parent from verified JWT',async()=>{vi.mocked(requireCalendarSyncRouteAuth).mockResolvedValue({authorized:true,kind:'email'} as any);expect((await relayPOST(req('POST',{action:'claim'},'/api/family/tasks/relay'))).status).toBe(401);expect((await POST(req('POST',draft))).status).toBe(403);const {taskActor}=await import('@/lib/family-mission/tasks-route');expect(await taskActor(req('POST',{person:'Cris'},'/api/family/records',{origin:'https://dashboard.test'}))).toBe('apavicio@gmail.com');});
it('enqueues one durable intent and rejects idempotency-key content conflicts',async()=>{const a=await enqueueTask('save',draft,'service','test-key-001');const b=await enqueueTask('save',draft,'service','test-key-001');expect(a).toEqual(b);expect(a.state).toBe('queued');expect(a).not.toHaveProperty('record');expect(sqlite.prepare('SELECT COUNT(*) n FROM google_tasks_commands').get().n).toBe(1);await expect(enqueueTask('save',{...draft,title:'Other'},'service','test-key-001')).rejects.toThrow();});
it('isolates operation lookup by server-derived actor',async()=>{const a=await enqueueTask('save',draft,'parent-a');await expect(getTaskOperation(a.operationId,'parent-b')).rejects.toThrow();});
it('fences stale revisions and unsupported recurrence/checklists',async()=>{await expect(enqueueTask('save',{...task,revision:99},'service')).rejects.toThrow('cambiado');for(const patch of [{recurrence:'daily'},{checklist:[{text:'x'}]},{status:'cancelled'}])await expect(enqueueTask('save',{...draft,...patch},'service')).rejects.toThrow();});
it('claims exclusively, retries only expired unstarted claims, and fences old lease tokens',async()=>{await enqueueTask('save',draft,'service');const a=await claim();expect(await claim()).toBeNull();sqlite.prepare('UPDATE google_tasks_commands SET lease_until=0').run();const b=await claim();expect(b.id).toBe(a.id);expect(b.leaseToken).not.toBe(a.leaseToken);await expect(begin(a)).rejects.toThrow();await begin(b);await expect(begin(b)).rejects.toThrow();});
it('invalidates the mirror before execution and prevents refresh during execution',async()=>{await enqueueTask('save',draft,'service');const a=await claim();await begin(a);await expect(taskSnapshot()).rejects.toThrow();await publish({records:[task]});await expect(taskSnapshot()).rejects.toThrow();await finish(a);expect((await taskSnapshot()).records).toEqual([task]);});
it('returns verified result on replay without reissuing a completed command even with stale mirror',async()=>{const a=await enqueueTask('save',draft,'service','retry-key-01');const c=await claim();await begin(c);await finish(c);sqlite.exec('UPDATE google_tasks_mirror SET refreshed_at=0');expect(await enqueueTask('save',draft,'service','retry-key-01')).toMatchObject({operationId:a.operationId,state:'done',record:task});expect(await claim()).toBeNull();await expect(finish(c)).rejects.toThrow();});
it('expired executing claims become ambiguous and are never replayed',async()=>{await enqueueTask('save',draft,'service');const c=await claim();await begin(c);sqlite.exec('UPDATE google_tasks_commands SET lease_until=0');expect(await claim()).toBeNull();expect(sqlite.prepare('SELECT state FROM google_tasks_commands').get().state).toBe('ambiguous');await expect(taskSnapshot()).rejects.toThrow();});
it('retains explicit failed and ambiguous operations without replay',async()=>{for(const state of ['failed','ambiguous']){const a=await enqueueTask('save',{...draft,title:state},'service');const c=await claim();await begin(c);await finish(c,state);expect(await getTaskOperation(a.operationId,'service')).toMatchObject({state});expect(await claim()).toBeNull();}});
it('queues update/complete/delete with the original Google identity',async()=>{for(const [action,raw] of [['save',{...task,title:'Updated'}],['save',{...task,status:'done'}],['delete',task]] as const){await enqueueTask(action,raw,'service');const c=await claim();expect(c.payload.record.id).toBe('google-id');await begin(c);await finish(c);}});
it('never migrates stale D1 tasks to Google',async()=>{expect((await flattenPOST(req('POST',{id:'stale'},'/api/family/records/flatten'))).status).toBe(409);expect(sqlite.prepare('SELECT COUNT(*) n FROM google_tasks_commands').get().n).toBe(0);});
it('completion digest follows Google completion timestamps without invented attribution',async()=>{await publish({records:[{...task,status:'done',completedAt:'2026-10-01T10:00:00Z'}]});expect(await readCompletionDigest('2026-10-01')).toMatchObject({store:'google-tasks',explicit:[],inferred:[{id:'google-id',channel:'other'}]});});

it('allows deliberate identical creation after completed deletion while preserving key retries',async()=>{const first=await enqueueTask('save',draft,'service','intent-first');const c=await claim();await begin(c);await finish(c);await enqueueTask('delete',task,'service','intent-delete');const d=await claim();await begin(d);await finish(d,'done',[],{ok:true} as any);expect(await enqueueTask('save',draft,'service','intent-first')).toMatchObject({operationId:first.operationId,state:'done'});const second=await enqueueTask('save',draft,'service','intent-second');expect(second.operationId).not.toBe(first.operationId);});
it('keyless deduplication ends with terminal success and retains ambiguous outcomes',async()=>{const a=await enqueueTask('save',draft,'service');expect(await enqueueTask('save',draft,'service')).toEqual(a);const c=await claim();await begin(c);await finish(c);expect((await enqueueTask('save',draft,'service')).operationId).not.toBe(a.operationId);});
it('a delayed capture cannot replace a post-mutation mirror or a newer refresh',async()=>{const early=await workerRelay({action:'snapshot-start'});await enqueueTask('save',draft,'service','generation-intent');const c=await claim();await begin(c);await finish(c,'done',[{...task,title:'New'}]);expect(await workerRelay({action:'snapshot',generation:early.generation,records:[task]})).toEqual({ok:false});expect((await taskSnapshot()).records[0].title).toBe('New');const older=await workerRelay({action:'snapshot-start'});await publish({records:[{...task,title:'Latest'}]});expect(await workerRelay({action:'snapshot',generation:older.generation,records:[task]})).toEqual({ok:false});expect((await taskSnapshot()).records[0].title).toBe('Latest');});
it('zero-row, duplicate and expired finish attempts cannot publish',async()=>{await enqueueTask('save',draft,'service');const c=await claim();await begin(c);await finish(c);const original=sqlite.prepare('SELECT * FROM google_tasks_mirror').get();await expect(finish(c,'done',[{...task,title:'Corrupt'}])).rejects.toThrow();expect(sqlite.prepare('SELECT * FROM google_tasks_mirror').get()).toEqual(original);await enqueueTask('save',{...draft,title:'another'},'service');const d=await claim();await begin(d);sqlite.exec('UPDATE google_tasks_commands SET lease_until=0');await expect(finish(d)).rejects.toThrow();await expect(taskSnapshot()).rejects.toThrow();});
it('normalizes unassigned owner for Dashboard writes',async()=>{const {commandPayload}=await import('@/lib/family-mission/tasks-relay');expect(commandPayload('save',{...draft,owner:'Sin asignar'}).record.owner).toBe('Sin asignar');expect(commandPayload('save',{...draft,owner:''}).record.owner).toBe('Sin asignar');});
it('meals retain CRUD, stale revision conflict and audit',async()=>{const meal=await saveRecord({kind:'meal',title:'Pasta',date:'2026-10-01',owner:'Familia',sourceKey:'meal:regression'});const updated=await saveRecord({...meal,title:'Arroz'});await expect(saveRecord({...meal,title:'Stale'})).rejects.toThrow('cambiado');await expect(removeRecord(meal.id,meal.revision)).rejects.toThrow('cambiado');await removeRecord(updated.id,updated.revision);expect(sqlite.prepare('SELECT action FROM family_audit WHERE record_id=? ORDER BY id').all(meal.id).map((r:any)=>r.action)).toEqual(['create','update','delete']);});

it('fences a competing transition occurring immediately before the finish transaction',async()=>{await enqueueTask('save',draft,'service');const c=await claim();await begin(c);const mirror=sqlite.prepare('SELECT * FROM google_tasks_mirror').get();beforeBatch=()=>sqlite.prepare("UPDATE google_tasks_commands SET state='ambiguous' WHERE id=?").run(c.id);await expect(finish(c,'done',[{...task,title:'Must not publish'}])).rejects.toThrow();expect(sqlite.prepare('SELECT * FROM google_tasks_mirror').get()).toEqual(mirror);expect(sqlite.prepare('SELECT state FROM google_tasks_commands WHERE id=?').get(c.id).state).toBe('ambiguous');});

it('rejects a capture delayed beyond freshness even without another mutation',async()=>{const ticket=await workerRelay({action:'snapshot-start'});sqlite.exec('UPDATE google_tasks_generation SET captured_at=0');expect(await workerRelay({action:'snapshot',generation:ticket.generation,records:[task]})).toEqual({ok:false});});
