// Google Tasks replaces the former D1 task/recurrence/audit persistence contract.
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {NextRequest} from 'next/server';
import {getCloudflareContext} from '@opennextjs/cloudflare';
import {requireCalendarSyncRouteAuth} from '@/lib/calendar-sync-auth';
import {verifiedFamilyEmail} from '@/lib/cloudflare-family-access';
import {GET,POST,DELETE} from '@/app/api/family/records/route';
import {POST as flattenPOST} from '@/app/api/family/records/flatten/route';
import {readRecords,saveRecord,removeRecord} from '@/lib/family-mission/store';
import {readCompletionDigest} from '@/lib/family-mission/completion-digest-store';
import {taskSnapshot} from '@/lib/family-mission/google-tasks';
vi.mock('server-only',()=>({}));
vi.mock('@/lib/family-mission/google-tasks',async importOriginal=>({...await importOriginal<typeof import('@/lib/family-mission/google-tasks')>(),taskSnapshot:vi.fn()}));
vi.mock('@opennextjs/cloudflare',()=>({getCloudflareContext:vi.fn()}));
vi.mock('@/lib/calendar-sync-auth',()=>({requireCalendarSyncRouteAuth:vi.fn()}));
vi.mock('@/lib/cloudflare-family-access',()=>({verifiedFamilyEmail:vi.fn()}));
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite');
let sqlite:any;
const task={kind:'task',id:'google-id',revision:101,title:'Disposable',date:'2026-10-01',time:'',notes:'',owner:'Familia',category:'family',reminderDays:0,status:'open',recurrence:'none',checklist:[],store:'google-tasks'};
const draft={...task,id:'',revision:0};
beforeEach(async()=>{
 sqlite=new DatabaseSync(':memory:');
 for(const migration of ['0001_family_mission.sql','0006_completion_provenance.sql','0008_google_tasks_relay.sql','0009_google_tasks_fences.sql','0010_drop_google_tasks_relay.sql'])sqlite.exec(readFileSync(new URL('../../migrations/'+migration,import.meta.url),'utf8'));
 const db={prepare(sql:string){const statement=sqlite.prepare(sql);let args:any[]=[];const bound={bind(...values:any[]){args=values;return bound;},async first(){return statement.get(...args)??null;},async all(){return {results:statement.all(...args)};},async run(){return {meta:{changes:statement.run(...args).changes}};}};return bound;},async batch(statements:any[]){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 vi.mocked(getCloudflareContext).mockResolvedValue({env:{FAMILY_DB:db}} as any);
 vi.mocked(requireCalendarSyncRouteAuth).mockResolvedValue({authorized:true,kind:'service'} as any);
 vi.mocked(verifiedFamilyEmail).mockResolvedValue('apavicio@gmail.com');
 vi.mocked(taskSnapshot).mockResolvedValue({records:[task],store:'google-tasks',mirror:false,refreshedAt:'now'} as never);
});
afterEach(()=>sqlite.close());
const req=(method:string,body:any,path='/api/family/records',headers={})=>new NextRequest('https://dashboard.test'+path,{method,headers,body:JSON.stringify(body)});
it('reads Google tasks and preserves non-task D1 records while excluding stale tasks',async()=>{
 for(const [id,kind] of [['stale','task'],['meal','meal']])sqlite.prepare('INSERT INTO family_records(id,kind,data,created_at,updated_at) VALUES(?,?,?,?,?)').run(id,kind,JSON.stringify({kind,title:id}),'now','now');
 expect((await readRecords()).map(r=>r.id)).toEqual(['meal','google-id']);
 const body=await (await GET(new NextRequest('https://dashboard.test/api/family/records'))).json();expect(body).toMatchObject({taskStore:'google-tasks',taskMirror:false});
 await expect(saveRecord({...draft,sourceKey:'old'})).rejects.toThrow('Google');await expect(removeRecord('stale',1)).rejects.toThrow('Google');
});
it('rejects unauthorized reads, writes and deletes',async()=>{vi.mocked(requireCalendarSyncRouteAuth).mockResolvedValue({authorized:false} as any);expect((await GET(new NextRequest('https://dashboard.test/api/family/records'))).status).toBe(401);expect((await POST(req('POST',draft))).status).toBe(401);expect((await DELETE(req('DELETE',task))).status).toBe(401);});
it('requires the Dashboard origin and derives the actor from the verified JWT',async()=>{vi.mocked(requireCalendarSyncRouteAuth).mockResolvedValue({authorized:true,kind:'email'} as any);expect((await POST(req('POST',draft))).status).toBe(403);const {taskActor}=await import('@/lib/family-mission/tasks-route');expect(await taskActor(req('POST',{person:'Cris'},'/api/family/records',{origin:'https://dashboard.test'}))).toBe('apavicio@gmail.com');});
it('completion digest follows Google completion timestamps without invented attribution',async()=>{vi.mocked(taskSnapshot).mockResolvedValue({records:[{...task,status:'done',completedAt:'2026-10-01T10:00:00Z'}]} as never);expect(await readCompletionDigest('2026-10-01')).toMatchObject({store:'google-tasks',explicit:[],inferred:[{id:'google-id',channel:'other'}]});});
it('never migrates stale D1 tasks to Google',async()=>{expect((await flattenPOST(req('POST',{id:'stale'},'/api/family/records/flatten'))).status).toBe(409);});
it('meals retain CRUD, stale revision conflict and audit',async()=>{const meal=await saveRecord({kind:'meal',title:'Pasta',date:'2026-10-01',owner:'Familia',sourceKey:'meal:regression'});const updated=await saveRecord({...meal,title:'Arroz'});await expect(saveRecord({...meal,title:'Stale'})).rejects.toThrow('cambiado');await expect(removeRecord(meal.id,meal.revision)).rejects.toThrow('cambiado');await removeRecord(updated.id,updated.revision);expect(sqlite.prepare('SELECT action FROM family_audit WHERE record_id=? ORDER BY id').all(meal.id).map((r:any)=>r.action)).toEqual(['create','update','delete']);});
