import {NextRequest,NextResponse} from 'next/server';
import {verifiedFamilyEmail} from '@/lib/cloudflare-family-access';
import {requireCalendarSyncRouteAuth} from '@/lib/calendar-sync-auth';
import {createConversation,deleteEmptyConversation,listChat,listConversations,type ChatConversation} from '@/lib/family-mission/chat-store';
import {legacyChat} from '@/lib/family-mission/legacy-chat';
export const dynamic='force-dynamic';
async function parent(req:NextRequest){const email=await verifiedFamilyEmail(req.headers.get('cf-access-jwt-assertion'));if(email)return ['apavicio@gmail.com','dapamar90@gmail.com'].includes(email)?'Dani' as const:'Cris' as const;const service=await requireCalendarSyncRouteAuth(req),requested=req.nextUrl.searchParams.get('person');return service.authorized&&service.kind==='service'&&(requested==='Dani'||requested==='Cris')?requested:null;}
export async function GET(req:NextRequest){const person=await parent(req);if(!person)return NextResponse.json({error:'Unauthorized'},{status:401});try{const query=(req.nextUrl.searchParams.get('q')||'').trim(),[current,old,unmapped]=await Promise.all([listConversations(person,query),legacyChat(person),listChat(person)]),history=[...old,...unmapped],matches=!query||history.some(item=>`${item.text} ${item.answer||''}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))),legacy:ChatConversation|undefined=history.length&&matches?{id:'legacy-'+person.toLowerCase(),person,title:'Conversación anterior',createdAt:new Date(Math.min(...history.map(item=>item.created))*1000).toISOString(),updatedAt:new Date(Math.max(...history.map(item=>item.created))*1000).toISOString()}:undefined;return NextResponse.json({person,conversations:[...current,...(legacy?[legacy]:[])].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))},{headers:{'Cache-Control':'private, no-store'}});}catch{return NextResponse.json({error:'No se pudieron cargar las conversaciones.'},{status:503});}}
export async function POST(req:NextRequest){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return NextResponse.json({error:'Unauthorized'},{status:403});const person=await parent(req);if(!person)return NextResponse.json({error:'Unauthorized'},{status:401});try{const body=await req.json(),title=typeof body.title==='string'?body.title:'Nueva conversación';return NextResponse.json({conversation:await createConversation(person,title)},{status:201});}catch{return NextResponse.json({error:'No se pudo crear la conversación.'},{status:503});}}
export async function DELETE(req:NextRequest){const person=await parent(req);if(!person)return NextResponse.json({error:'Unauthorized'},{status:401});try{const body=await req.json();if(typeof body.id!=='string')return NextResponse.json({error:'Datos no válidos.'},{status:400});await deleteEmptyConversation(person,body.id);return NextResponse.json({ok:true});}catch{return NextResponse.json({error:'No se pudo eliminar.'},{status:409});}}
