'use client';
import {useEffect,useState} from 'react';
import {DASHBOARD_REFRESH} from './dashboard-refresh';
import {sortedActivities,activityDeadline,activityTimeLabel,type ActivityPlan} from '@/lib/family-mission/activity-model';
import {dateKey} from '@/lib/family-mission/model';
import './activities.css';
const label=(day:string)=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',timeZone:'Europe/Madrid'}).format(new Date(day+'T12:00:00Z'));
export default function ActivityPlans(){
 const [plans,setPlans]=useState<ActivityPlan[]>([]),[checked,setChecked]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(false),[loading,setLoading]=useState(true),[expanded,setExpanded]=useState(false);
 useEffect(()=>{let active=true;async function load(){try{const r=await fetch('/api/family/activity-plans',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();if(active){setPlans(d.plans);setChecked(d.checkedAt);setError(false);}}catch{if(active)setError(true);}finally{if(active)setLoading(false);}}window.addEventListener(DASHBOARD_REFRESH,load);void load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer);window.removeEventListener(DASHBOARD_REFRESH,load);};},[]);
 const visible=sortedActivities(plans,dateKey()).filter(p=>filter==='all'||filter==='soon'&&activityDeadline(p)||filter==='indoor'&&p.indoor);
 return <section className="ap-section" aria-label="Propuestas de planes familiares"><header><div><span className="ap-eyebrow">TIEMPO JUNTOS</span><h2>¿Qué hacemos en familia?</h2><p>Primero, los planes que no conviene dejar pasar.</p></div></header><nav className="ap-filters" aria-label="Filtrar propuestas">{[['all','Todos'],['soon','Con fecha límite'],['indoor','Si llueve']].map(([k,t])=><button key={k} aria-pressed={filter===k} onClick={()=>setFilter(k)}>{t}</button>)}</nav>
 {error?<p role="alert">No se pudieron actualizar las propuestas.</p>:loading?<p>Cargando propuestas…</p>:!visible.length?<p>No hay propuestas en este filtro.</p>:<div className="ap-grid">{visible.slice(0,expanded?visible.length:4).map(p=>{const deadline=activityDeadline(p);return <article className="ap-card" key={p.id}><div className={'ap-art '+(p.indoor?'indoor':'')+(p.photo?' has-photo':'')}>{p.photo?<img src={p.photo} alt={p.photoAlt||p.location} loading="lazy"/>:<span aria-hidden="true">{p.icon}</span>}<strong>{p.window}</strong>{p.photo&&<small>Foto del lugar</small>}</div><div className="ap-body"><span className={'ap-badge '+(deadline?'urgent':'')}>{deadline?(deadline===p.bookingDeadline?'Reservar antes del ':'Último día · ')+label(deadline):p.status==='pending'?'Programa pendiente':'Plan flexible'}</span><div className={'ap-time ap-time-'+p.timeOfDay}>{activityTimeLabel(p)}</div><h3>{p.title}</h3><p>{p.description}</p><div className="ap-facts"><div><small>Desde casa</small><strong>{p.distanceKm===null?'Por calcular':`≈ ${p.distanceKm.toLocaleString('es-ES')} km en ${p.distanceMode}`}</strong></div><div><small>Precio orientativo</small><strong>{p.price}</strong></div><div><small>Duración</small><strong>{p.duration}</strong></div><div><small>Estado</small><strong>Propuesta · sin reservar</strong></div></div><details><summary>Edades y detalles</summary><p>{p.ageNote}</p><p>{p.note}</p>{p.photoSource&&<a href={p.photoSource} target="_blank" rel="noopener noreferrer" className="ap-photo-credit">Foto: {p.photoCredit}</a>}</details><a href={p.url} target="_blank" rel="noopener noreferrer">Ver programa y entradas ↗</a><a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.location)} target="_blank" rel="noopener noreferrer">Ver ubicación ↗</a></div></article>;})}</div>}
 {visible.length>4&&<button className="ap-expand" onClick={()=>setExpanded(!expanded)}>{expanded?'Ver menos':`Ver las ${visible.length} propuestas`}</button>}<p className="ap-foot">Distancias orientativas en coche desde casa, calculadas con OpenStreetMap/OSRM{checked?' · Revisión '+label(checked):''}. Comprobar precios, edades y disponibilidad antes de reservar. Los planes caducados se ocultan.</p></section>;
}
