'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {CalendarDays,CheckCircle2,Lightbulb,Plus,Sun,Trash2,Utensils} from 'lucide-react';
import type {AgentCapability,CapabilityStatus} from '@/lib/family-mission/capability-store';
import './mission.css';
import './capability-backlog.css';
import ApprovalTray from './ApprovalTray';
const labels:Record<CapabilityStatus,string>={idea:'Idea',planned:'Próxima',in_progress:'En marcha',done:'Hecha'};
export default function CapabilityBacklog(){const [items,setItems]=useState<AgentCapability[]>([]),[title,setTitle]=useState(''),[notes,setNotes]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/family/capabilities',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setItems(j.items);}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar.');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 async function add(e:FormEvent){e.preventDefault();if(!title.trim())return;setBusy(true);setError('');try{const r=await fetch('/api/family/capabilities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,notes})}),j=await r.json();if(!r.ok)throw new Error(j.error);setItems(x=>[j.item,...x]);setTitle('');setNotes('');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 async function status(item:AgentCapability,value:CapabilityStatus){const old=items;setItems(x=>x.map(v=>v.id===item.id?{...v,status:value}:v));const r=await fetch('/api/family/capabilities',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,status:value})});if(!r.ok){setItems(old);setError('No se pudo actualizar.');}}
 async function remove(id:string){if(!confirm('¿Eliminar esta habilidad del backlog?'))return;const r=await fetch('/api/family/capabilities',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok)setItems(x=>x.filter(v=>v.id!==id));else setError('No se pudo eliminar.');}
 return <div className="mission"><ApprovalTray/><aside className="mc-sidebar"><Link className="mc-brand" href="/"><span>a.</span>apalas<span className="mc-brand-dot">●</span></Link><div className="mc-sidebar-label">NUESTRO DÍA A DÍA</div><nav><Link href="/"><Sun size={20}/>Hoy y mañana</Link><Link href="/family-calendar"><CalendarDays size={20}/>Calendario</Link><Link href="/week"><Utensils size={20}/>Plan semanal</Link><Link className="active" href="/agent-backlog"><Lightbulb size={20}/>Ideas para Rufus</Link></nav><div className="mc-sidebar-bottom"><div className="mc-hermes"><span className="mc-live-dot"/>Rufus · Family COO<small>Lo que queréis que aprenda o haga después.</small></div></div></aside><div className="mc-workspace"><header className="mc-topbar"><span>EN FAMILIA <span className="mc-slash">/</span> Rufus</span><div><a href="/cdn-cgi/access/logout">Salir</a></div></header><main className="mc-content cb-page"><div className="mc-page-heading"><div><div className="mc-eyebrow">MEJORAS QUE QUEREMOS</div><h1>Ideas para Rufus</h1><p>Un backlog compartido para guardar, priorizar y seguir nuevas capacidades.</p></div></div>{error&&<div className="mc-error" role="alert">{error}</div>}<form className="mc-card cb-add" onSubmit={add}><div><label>Nueva idea<input maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="¿Qué debería poder hacer Rufus?"/></label><label>Detalles <small>(opcional)</small><textarea rows={2} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Cómo os ayudaría o qué debería tener en cuenta."/></label></div><button className="mc-primary" disabled={busy||!title.trim()}><Plus size={18}/>{busy?'Guardando…':'Añadir'}</button></form>{loading?<div className="mc-loading">Cargando ideas…</div>:<div className="cb-grid">{(['in_progress','planned','idea','done'] as CapabilityStatus[]).map(group=><section className="mc-card cb-column" key={group}><header><span className={'cb-dot '+group}/><h2>{labels[group]}</h2><small>{items.filter(x=>x.status===group).length}</small></header><div>{items.filter(x=>x.status===group).map(item=><article className="cb-item" key={item.id}><h3>{item.title}</h3>{item.notes&&<p>{item.notes}</p>}<footer><select aria-label={'Estado de '+item.title} value={item.status} onChange={e=>void status(item,e.target.value as CapabilityStatus)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button aria-label={'Eliminar '+item.title} onClick={()=>void remove(item.id)}><Trash2 size={16}/></button></footer></article>)}{!items.some(x=>x.status===group)&&<div className="cb-empty"><CheckCircle2 size={20}/>Nada aquí</div>}</div></section>)}</div>}<footer className="mc-footer"><span><span className="mc-live-dot"/> Backlog compartido por Dani y Cris.</span></footer></main></div></div>;
}
