 'use client';
import {useEffect,useState} from 'react';
import {DASHBOARD_REFRESH} from './dashboard-refresh';
import './digest.css';
import {Package,Receipt,CalendarDays,FileText} from 'lucide-react';
import type {DigestItem} from '@/lib/family-mission/digest-model';
import type {FamilyRecord} from '@/lib/family-mission/model';
export default function DailyDigest({day,events,onEvent}:{day:string;events:FamilyRecord[];onEvent:(r:FamilyRecord)=>void}){
 const [items,setItems]=useState<DigestItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [filter,setFilter]=useState('all');
 useEffect(()=>{let active=true;setLoading(true);async function load(){try{const r=await fetch('/api/family/digest?date='+day,{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();if(active){setItems(d.items);setError(false);}}catch{if(active)setError(true);}finally{if(active)setLoading(false);}}window.addEventListener(DASHBOARD_REFRESH,load);void load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer);window.removeEventListener(DASHBOARD_REFRESH,load);};},[day]);
 const visible=items.filter(i=>filter==='all'||i.kind===filter);const showEvents=filter==='all'||filter==='event';const total=visible.length+(showEvents?events.length:0);
 return <section className="mc-digest"><div className="mc-section-heading"><h2>Resumen del día</h2><span>{items.length+events.length} novedades</span></div><div className="mc-card"><div className="mc-digest-filters" role="group" aria-label="Filtrar resumen">{[['all','Todo'],['delivery','Entregas'],['receipt','Recibos'],['event','Agenda']].map(([k,label])=><button key={k} aria-pressed={filter===k} className={filter===k?'selected':''} onClick={()=>setFilter(k)}>{label}</button>)}</div>
 {error?<p className="mc-digest-empty" role="alert">No se pudo actualizar el resumen.</p>:loading?<p className="mc-digest-empty">Cargando el día…</p>:!total?<p className="mc-digest-empty">Sin novedades de este tipo.</p>:<div className="mc-digest-list">{visible.map(i=>{const Icon=i.kind==='delivery'?Package:i.kind==='receipt'?Receipt:CalendarDays;return <article className="mc-digest-item" key={i.id}><div className={'mc-digest-icon '+i.kind}><Icon size={20}/></div><div><div className="mc-digest-title"><h3>{i.title}</h3>{i.amountMinor!==null&&<strong>{new Intl.NumberFormat('es-ES',{style:'currency',currency:i.currency}).format(i.amountMinor/100)}</strong>}</div>{i.details&&<p>{i.details}</p>}<small>{i.merchant||i.source}{i.status?' · '+i.status:''}</small>{i.kind==='receipt'&&<><span className="mc-receipt-pending">{i.financeStatus==='matched'?'Vinculado en Finenance':i.financeReceiptId?'En Finenance · pendiente del banco':'Pendiente de vincular al banco'}</span>{i.financeReceiptId&&<a href="https://finenance.apaniel.dev" target="_blank" rel="noopener noreferrer" className="mc-receipt-pending">Abrir Finenance ↗</a>}</>}{!!i.documents?.length&&<div className="mc-digest-docs">{i.documents.map(d=><a key={d.id} href={'/api/family/documents/'+d.id}><FileText size={15}/>{d.filename}</a>)}</div>}</div></article>;})}
 {showEvents&&events.map(e=><button className="mc-digest-item mc-digest-event" key={e.id} onClick={()=>onEvent(e)}><div className="mc-digest-icon event"><CalendarDays size={20}/></div><div><h3>{e.title}</h3><small>{e.time||'Todo el día'}{!e.confirmed?' · Por confirmar':''}</small></div></button>)}</div>}
 <p className="mc-digest-foot">Lo cotidiano queda aquí. Los recibos se guardan aunque el movimiento bancario llegue después.</p></div></section>;
}
