'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,Send,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import './family-chat.css';
type Message={id:string;text:string;answer:string|null;status:string;created:number};
export default function FamilyChat(){
 const [open,setOpen]=useState(false),[person,setPerson]=useState(''),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const bottom=useRef<HTMLDivElement>(null),requestId=useRef<string|null>(null);
 const pending=messages.some(m=>m.status==='pending');
 async function load(){try{const r=await fetch('/api/family/chat',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(d.messages);setPerson(d.person);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo conectar.');}}
 useEffect(()=>{if(!open)return;void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},4000);return()=>clearInterval(timer);},[open]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'});},[messages.length,messages[messages.length-1]?.status,open]);
 async function send(){if(!text.trim()||busy||pending)return;setBusy(true);setError('');requestId.current ||= crypto.randomUUID();try{const r=await fetch('/api/family/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,id:requestId.current})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(d.messages);setPerson(d.person);setText('');requestId.current=null;}catch(e){setError(e instanceof Error?e.message:'No se pudo enviar.');}finally{setBusy(false);}}
 return <><button className="fc-launch" onClick={()=>setOpen(true)}><MessageCircle size={21}/> Hablar con Rufus</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="fc-panel"><header className="fc-header"><span className="fc-avatar">R</span><div><DialogTitle>Rufus · Familia</DialogTitle><DialogDescription>{person?`Estás hablando como ${person}`:'Tu asistente familiar'}</DialogDescription></div></header><div className="fc-history" role="log" aria-live="polite">{!messages.length&&!error&&<div className="fc-welcome"><h3>Un poco menos en tu cabeza.</h3><p>Planes, comidas, calendario y todo lo de las peques.</p><div>{['¿Qué tenemos mañana?','Dame ideas para el fin de semana','Ayúdame con las cenas'].map(t=><button key={t} onClick={()=>setText(t)}>{t}</button>)}</div></div>}{messages.map(m=><div key={m.id} className="fc-exchange"><div className="fc-bubble fc-you">{m.text}</div>{m.answer&&<div className="fc-bubble fc-rufus">{m.answer}</div>}{m.status==='pending'&&<div className="fc-wait" role="status">Rufus está preparando tu respuesta…</div>}</div>)}<div ref={bottom}/></div>{error&&<p className="fc-error" role="alert">{error}</p>}<form className="fc-compose" onSubmit={e=>{e.preventDefault();void send();}}><textarea aria-label="Mensaje para Rufus" placeholder="Cuéntame, ¿qué necesitas?" value={text} maxLength={4000} rows={2} onChange={e=>{setText(e.target.value);requestId.current=null;}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><button type="submit" disabled={busy||pending||!text.trim()} aria-label="Enviar mensaje"><Send size={20}/></button></form><p className="fc-footnote">Conversación de {person||'tu cuenta'} · Calendario y tareas compartidos</p></DialogContent></Dialog></>;
}
