'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {CalendarDays,ChevronLeft,ChevronRight,Plus,Sun,Utensils,ArrowUpRight,Gift,RefreshCw,CheckCheck,Trash2,X,Lightbulb} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {dateKey,addDays,occursOn,calendarEventStyle,calendarDayStyle,isCalendarDayBlock,calendarTimeLabel,taskAgeLabel,type FamilyRecord,type Kind} from '@/lib/family-mission/model';
import './mission.css';
import DailyDigest from './DailyDigest';
import ActivityPlans from './ActivityPlans';
import {recordSource,calendarLoadRanges,taskEditorContext,normalTasks,pendingTasks,isCompleted,prepareCompletion,editorSaveAction} from '@/lib/family-mission/attention';
import FamilyChat from './FamilyChat';
import DashboardLive from './DashboardLive';
import ApprovalTray from './ApprovalTray';
import {DASHBOARD_REFRESH,everyVisible} from './dashboard-refresh';
const owners=['Dani','Cris','Saida','Familia','Sin asignar'];
const categories:Record<string,string>={family:'En familia',school:'Colegio',birthday:'Cumpleaños',holiday:'Vacaciones y festivos',return:'Devolución',home:'Casa'};
const dayLabel=(d:string,options:Intl.DateTimeFormatOptions={weekday:'long',day:'numeric',month:'long'})=>new Intl.DateTimeFormat('es-ES',{...options,timeZone:'Europe/Madrid'}).format(new Date(d+'T12:00:00Z'));
const weekStart=(d:string)=>addDays(d,-((new Date(d+'T12:00:00Z').getUTCDay()+6)%7));
function blank(kind:Kind,day:string):FamilyRecord{return {id:'',revision:0,kind,title:'',date:day,owner:kind==='task'?'Dani':'Familia',status:'open',category:'family',notes:'',checklist:[],audience:'adults',slot:'dinner',recurrence:'none',source:'Familia',confirmed:true,reminderDays:kind==='event'?7:0};}
export default function MissionControl({view}:{view:'today'|'calendar'|'week'}){return <Board view={view}/>;}
function Board({view}:{view:'today'|'calendar'|'week'}){
 const [revision,setRevision]=useState(0);const [today,setToday]=useState(dateKey());const [day,setDay]=useState(dateKey());const [records,setRecords]=useState<FamilyRecord[]>([]);const [google,setGoogle]=useState<FamilyRecord[]>([]);
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [editing,setEditing]=useState<FamilyRecord|null>(null);const [busy,setBusy]=useState(false);const [filter,setFilter]=useState('Todos');const [category,setCategory]=useState('all');const [confirmDelete,setConfirmDelete]=useState(false);
 const [editingDay,setEditingDay]=useState(day);
 const headers=()=>({'Content-Type':'application/json'});
 const load=useCallback(async()=>{setError('');try{const r=await fetch('/api/family/records',{headers:headers(),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setRecords(j.records);}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar los datos.');}finally{setLoading(false);}},[]);
 useEffect(()=>{const refresh=()=>{setToday(dateKey());void load();setRevision(v=>v+1);};window.addEventListener(DASHBOARD_REFRESH,refresh);void load();const stop=everyVisible(()=>{setToday(dateKey());void load();setRevision(v=>v+1);},60000);return()=>{stop();window.removeEventListener(DASHBOARD_REFRESH,refresh);};},[load]);
 useEffect(()=>{
  let active=true;
  Promise.all(calendarLoadRanges(day,today,view==='today').map(async({from,to})=>{
   const response=await fetch('/api/family/calendar?from='+from+'&to='+to,{headers:headers(),cache:'no-store'});
   if(!response.ok)throw new Error();
   return (await response.json()).events as FamilyRecord[];
  })).then(groups=>{if(active)setGoogle(Array.from(new Map(groups.flat().map(r=>[r.id,r])).values()));})
   .catch(()=>{if(active)setNotice('Google Calendar no se ha podido actualizar. Tus planes siguen guardados.');});
  return()=>{active=false;};
 },[day,today,view,revision]);
 async function save(value:FamilyRecord & {completeOn?:string},close=true){setBusy(true);setError('');try{const r=await fetch('/api/family/records',{method:'POST',headers:headers(),body:JSON.stringify(value)});const j=await r.json();if(!r.ok)throw new Error(j.error);const saved:FamilyRecord[]=j.records||[j.record];setRecords(current=>[...saved,...current.filter(x=>!saved.some(r=>r.id===x.id))]);if(close)setEditing(null);setNotice('Guardado.');return j.record as FamilyRecord;}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');return false;}finally{setBusy(false);}}
 async function remove(){if(!editing)return;setBusy(true);try{const r=await fetch('/api/family/records',{method:'DELETE',headers:headers(),body:JSON.stringify({id:editing.id,revision:editing.revision})});if(!r.ok)throw new Error();setRecords(x=>x.filter(v=>v.id!==editing.id));setEditing(null);setConfirmDelete(false);setNotice('Eliminado.');}catch{setError('No se pudo eliminar. Actualiza la página.');}finally{setBusy(false);}}
 function add(kind:Kind,date=day,patch:Partial<FamilyRecord>={}){setConfirmDelete(false);setEditingDay(date);setEditing({...blank(kind,date),...patch});}
 function open(r:FamilyRecord,d=day){const context=taskEditorContext(r,d,records);setConfirmDelete(false);setEditingDay(context.day);setEditing({...context.record,status:context.record.kind==='task'&&context.record.status==='waiting'?'open':context.record.status});}
 async function complete(r:FamilyRecord,d:string,close=false){
  try{
   const prepared=close?{action:editorSaveAction(r,d,records)}:await prepareCompletion(r,d,records,value=>save(value,false));
   if(prepared?.action.type==='save')await save(prepared.action.record,close);
  }catch(e){setError(e instanceof Error?e.message:'No se pudo completar.');}
 }
 async function submitEditing(r:FamilyRecord){if(r.kind==='task'&&r.status==='done')await complete(r,editingDay,true);else await save(r);}
 async function toggleTask(r:FamilyRecord,d:string){
  if(r.status==='done')await save({...r,status:'open',completionDecision:undefined},false);
  else await complete(r,d);
 }
 const completed=(r:FamilyRecord,d:string)=>isCompleted(r,records,d);
 const tasks=(d:string)=>(view==='today'?pendingTasks(records,d):normalTasks(records,d,today).filter(r=>occursOn(r,d))).filter(r=>filter==='Todos'||r.owner===filter);
 const events=(d:string)=>[...records,...google].filter(r=>r.kind==='event'&&r.status!=='cancelled'&&occursOn(r,d)&&(category==='all'||r.category===category)).sort((a,b)=>(a.time||'').localeCompare(b.time||''));
 const meals=(d:string,audience:string)=>records.filter(r=>r.kind==='meal'&&r.status!=='cancelled'&&r.date===d&&r.audience===audience).sort((a,b)=>a.slot.localeCompare(b.slot));
 const days=Array.from({length:7},(_,i)=>addDays(weekStart(day),i));const pending=tasks(day).length;
 const monthStart=day.slice(0,7)+'-01';const gridStart=weekStart(monthStart);const monthDays=Array.from({length:42},(_,i)=>addDays(gridStart,i));
 function taskRow(r:FamilyRecord,d:string){const isDone=completed(r,d);const age=r.recurrence==='none'&&!isDone?taskAgeLabel(r.date,d):'';return <div className={'mc-task '+(isDone?'is-done':'')} key={r.id}>
 <Checkbox checked={isDone} disabled={busy||r.recurrence!=='none'&&isDone} aria-label={(isDone?'Reabrir ':'Completar ')+r.title} onCheckedChange={()=>void toggleTask(r,d)}/>
 <button className="mc-task-body" onClick={()=>open(r,d)}><strong>{r.title}</strong><span>{r.time&&`${r.time} · `}{r.owner}</span>{age&&<small className={'mc-task-age '+(r.date<addDays(d,-2)?'is-old':'')}>{age}</small>}{r.notes&&<p>{r.notes.slice(0,110)}</p>}</button>
 <span className={'mc-avatar '+(r.owner==='Cris'?'rose':r.owner==='Saida'?'gold':'')}>{r.owner.slice(0,1)}</span></div>;}
 function eventRow(r:FamilyRecord){return <button className={'mc-event '+r.category} style={{borderLeftColor:calendarEventStyle(r)?.backgroundColor||'#597bdc'}} key={r.id} onClick={()=>open(r)}><span className="mc-event-time">{calendarTimeLabel(r)}</span><div><strong>{r.title}</strong><span>{categories[r.category]||'Google Calendar'}{!r.confirmed?' · Por confirmar':''}</span></div><ArrowUpRight size={16}/></button>;}
 const empty=(text:string)=><div className="mc-empty"><CheckCheck size={24}/><p>{text}</p></div>;
 return <div className="mission">
 <aside className="mc-sidebar"><Link className="mc-brand" href="/"><span>a.</span>apalas<span className="mc-brand-dot">●</span></Link><div className="mc-sidebar-label">NUESTRO DÍA A DÍA</div><nav aria-label="Principal">{[['/',Sun,'Hoy y mañana','today'],['/family-calendar',CalendarDays,'Calendario','calendar'],['/week',Utensils,'Plan semanal','week'],['/agent-backlog',Lightbulb,'Ideas para Rufus','backlog']].map(([href,Icon,label,key])=>{const I=Icon as typeof Sun;return <Link key={String(key)} href={String(href)} className={view===key?'active':''}><I size={20}/>{String(label)}</Link>;})}</nav><div className="mc-sidebar-bottom"><div className="mc-hermes"><span className="mc-live-dot"/>Rufus · Family COO<small>Un lugar para tenerlo todo a mano.</small></div></div></aside>
 <div className="mc-workspace"><header className="mc-topbar"><span>EN FAMILIA <span className="mc-slash">/</span> {view==='today'?'El día a día':view==='calendar'?'Nuestros planes':'A la mesa'}</span><div><span className="mc-today-label">{dayLabel(today,{day:'numeric',month:'short'})}</span><a href="/cdn-cgi/access/logout">Salir</a></div></header>
 <main className="mc-content"><div className="mc-page-heading"><div><div className="mc-eyebrow">{view==='today'?'UN POCO DE ORDEN, MÁS TIEMPO JUNTOS':view==='calendar'?'LO IMPORTANTE, A LA VISTA':'LA SEMANA, RESUELTA'}</div><h1>{view==='today'?'Hoy y mañana':view==='calendar'?'Calendario familiar':'¿Qué comemos?'}</h1><p>{view==='today'?'Lo pendiente, hasta que esté hecho.':view==='calendar'?'Cumpleaños, colegio, vacaciones y nuestros planes.':'Un menú para vosotros. Otro para las peques.'}</p></div><Button className="mc-primary" onClick={()=>add(view==='calendar'?'event':view==='week'?'meal':'task')}><Plus size={18}/>{view==='calendar'?'Añadir plan':view==='week'?'Añadir comida':'Añadir tarea'}</Button></div>
 {error&&<div className="mc-error" role="alert">{error}<button onClick={()=>void load()}>Volver a cargar</button></div>}{notice&&<div className="mc-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Cerrar aviso"><X size={15}/></button></div>}
 <div className="mc-toolbar"><div className="mc-date-nav"><button aria-label="Anterior" onClick={()=>setDay(view==='calendar'?new Date(Date.UTC(Number(day.slice(0,4)),Number(day.slice(5,7))-2,1)).toISOString().slice(0,10):addDays(day,view==='week'?-7:-1))}><ChevronLeft size={18}/></button><strong>{view==='week'?`${dayLabel(days[0],{day:'numeric',month:'short'})} — ${dayLabel(days[6],{day:'numeric',month:'short'})}`:view==='calendar'?dayLabel(monthStart,{month:'long',year:'numeric'}):day===today?'Hoy · '+dayLabel(day,{day:'numeric',month:'long'}):dayLabel(day,{weekday:'long',day:'numeric',month:'long'})}</strong><button aria-label="Siguiente" onClick={()=>setDay(view==='calendar'?new Date(Date.UTC(Number(day.slice(0,4)),Number(day.slice(5,7)),1)).toISOString().slice(0,10):addDays(day,view==='week'?7:1))}><ChevronRight size={18}/></button><button className="mc-today-button" onClick={()=>setDay(today)}>Hoy</button></div>{view==='today'?<div className="mc-filters">{['Todos','Dani','Cris','Saida'].map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}</button>)}</div>:view==='calendar'?<select aria-label="Tipo de evento" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todos los planes</option>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>:null}</div>
 {loading?<div className="mc-loading" role="status"><RefreshCw size={20} className="animate-spin"/> Cargando vuestros planes…</div>:<>
 {view==='today'&&<ActivityPlans/>}
 {view==='today'&&<div className="mc-today-grid"><section><DailyDigest day={day} events={events(day)} onEvent={open}/><div className="mc-section-heading"><h2>Tareas pendientes</h2><span>{pending?`${pending} pendiente${pending!==1?'s':''}`:'Todo al día'}</span></div><div className="mc-card mc-task-list">{tasks(day).length?tasks(day).map(r=>taskRow(r,day)):empty('No hay tareas pendientes para este día.')}<button className="mc-add-row" onClick={()=>add('task')}><Plus size={17}/> Añadir algo a la lista</button></div><div className="mc-section-heading"><h2>A la mesa</h2><Link href="/week">Ver la semana <ArrowUpRight size={15}/></Link></div><div className="mc-meal-pair">{['adults','kids'].map(a=><div className="mc-card mc-meal-today" key={a}><span className={'mc-tag '+(a==='kids'?'pink':'blue')}>{a==='kids'?'LAS PEQUES':'LOS MAYORES'}</span>{meals(day,a).length?meals(day,a).map(m=><button key={m.id} onClick={()=>open(m)}><small>{m.slot==='lunch'?'Comida':'Cena'}</small><h3>{m.title}</h3>{m.notes&&<p>{m.notes}</p>}</button>):<button onClick={()=>add('meal',day,{audience:a as any})}><h3>Por decidir</h3><p>Añadir al menú <Plus size={15}/></p></button>}</div>)}</div></section>
</div>}
 {view==='calendar'&&<><div className="mc-calendar-card"><div className="mc-calendar-weekdays">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=><span key={d}>{d}</span>)}</div><div className="mc-calendar-grid">{monthDays.map(d=><div key={d} className={'mc-calendar-cell '+(d===today?'is-today ':'')+(d===day?'is-selected ':'')+(d.slice(0,7)!==day.slice(0,7)?'outside':'')} style={calendarDayStyle(events(d))}><button className="mc-day-number" onClick={()=>setDay(d)} aria-label={dayLabel(d)} aria-pressed={d===day}>{Number(d.slice(-2))}</button><button className="mc-mobile-day" onClick={()=>setDay(d)} aria-label={dayLabel(d)+` · ${events(d).length} eventos`} aria-pressed={d===day}><span className="mc-mobile-date">{Number(d.slice(-2))}</span><span className="mc-day-dots" aria-hidden="true">{events(d).filter(r=>!isCalendarDayBlock(r)).slice(0,3).map(r=><i key={r.id} style={{backgroundColor:calendarEventStyle(r)?.backgroundColor||'#597bdc'}}/>)}{events(d).filter(r=>!isCalendarDayBlock(r)).length>3&&<small>+</small>}</span></button>{events(d).slice(0,3).map(r=><button className={'mc-calendar-pill '+r.category} style={calendarEventStyle(r)} title={calendarTimeLabel(r)+' · '+r.title} key={r.id} onClick={()=>open(r)}>{!r.allDay&&r.time&&<span>{r.time} </span>}{r.title}</button>)}{events(d).length>3&&<button className="mc-more" onClick={()=>setDay(d)}>+{events(d).length-3} más</button>}<button className="mc-cell-add" aria-label={'Añadir plan el '+dayLabel(d)} onClick={()=>add('event',d)}><Plus size={14}/></button></div>)}</div></div><div className="mc-calendar-bottom"><section className="mc-card mc-day-agenda" aria-label="Planes del día"><header><div><span className="mc-eyebrow">PLANES DEL DÍA</span><h2>{dayLabel(day)}</h2></div><button onClick={()=>add('event',day)} aria-label="Añadir un plan a este día"><Plus size={20}/></button></header>{events(day).length?events(day).map(eventRow):empty('Sin planes. Un día para improvisar.')}</section><div className="mc-calendar-tips"><Gift/><div><h3>Que no se nos pase.</h3><p>Los cumpleaños pueden repetirse cada año y avisar con tiempo para preparar un regalo.</p></div><Button variant="outline" onClick={()=>add('event',day,{category:'birthday',recurrence:'yearly',reminderDays:14})}>Añadir cumpleaños</Button></div></div></>}
 {view==='week'&&<><div className="mc-week-grid">{days.map(d=><section className={'mc-week-day '+(d===today?'is-today':'')} key={d}><header><span>{dayLabel(d,{weekday:'short'})}</span><strong>{Number(d.slice(-2))}</strong>{d===today&&<small>Hoy</small>}</header><div className="mc-week-tasks"><h3>TAREAS</h3>{tasks(d).map(r=><button key={r.id} onClick={()=>open(r,d)}><span className={'mc-owner-dot '+(r.owner==='Cris'?'pink':'')}/>{r.title}</button>)}<button className="mc-week-add" onClick={()=>add('task',d)}><Plus size={14}/> Tarea</button></div>{['adults','kids'].map(a=><div className={'mc-week-meals '+a} key={a}><h3>{a==='kids'?'LAS PEQUES':'LOS MAYORES'}</h3>{['lunch','dinner'].map(slot=><div className="mc-meal-slot" key={slot}><small>{slot==='lunch'?'Comida':'Cena'}</small>{meals(d,a).filter(m=>m.slot===slot).map(m=><button key={m.id} onClick={()=>open(m)}>{m.title}</button>)}{!meals(d,a).some(m=>m.slot===slot)&&<button className="mc-week-add" aria-label={`${slot==='lunch'?'Comida':'Cena'} ${a==='kids'?'peques':'mayores'} ${dayLabel(d)}`} onClick={()=>add('meal',d,{audience:a as any,slot:slot as any})}><Plus size={14}/> Planear</button>}</div>)}</div>)}</section>)}</div><div className="mc-week-note"><Utensils size={18}/><span>Guarda ingredientes y preparación en las notas de cada comida. Rufus podrá reunirlos para hacer la compra.</span></div></>}
 </>}
 <footer className="mc-footer"><span><span className="mc-live-dot"/> Vuestros planes, guardados y compartidos.</span><a href="https://calendar.google.com/calendar/r?authuser=losapalas%40gmail.com" target="_blank" rel="noreferrer">Google Calendar <ArrowUpRight size={14}/></a></footer></main></div>
 <DashboardLive editing={!!editing||busy}/><ApprovalTray/><FamilyChat/><Dialog open={!!editing} onOpenChange={v=>{if(!v){setEditing(null);setConfirmDelete(false);}}}><DialogContent className="mc-dialog"><DialogHeader><DialogTitle>{editing?.readOnly?'Google Calendar':editing?.id?'Editar':'Añadir'} {editing?.kind==='meal'?'comida':editing?.kind==='task'?'tarea':'plan'}</DialogTitle><DialogDescription>{editing?.readOnly?'Este evento viene de Google Calendar. Modifícalo allí.':editing?.kind==='event'?'Los planes nuevos se guardan en el calendario familiar de esta página.':'Los cambios se comparten con la familia y Rufus.'}</DialogDescription></DialogHeader>{editing&&<form onSubmit={e=>{e.preventDefault();void submitEditing(editing);}} className="mc-form"><fieldset disabled={busy||editing.readOnly}>
 <label>¿Qué hay que {editing.kind==='meal'?'preparar':editing.kind==='event'?'recordar':'hacer'}?<input autoFocus required maxLength={200} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} placeholder={editing.kind==='meal'?'Pasta con verduras':editing.kind==='event'?'Cumpleaños de…':'Preparar la mochila de Paula'}/></label>
 <div className="mc-form-row"><label>Fecha<input required type="date" value={editing.date} onChange={e=>setEditing({...editing,date:e.target.value})}/></label>{editing.kind==='event'?<label>Hasta el día<input type="date" min={editing.date} value={editing.endDate||''} onChange={e=>setEditing({...editing,endDate:e.target.value})}/></label>:<label>Responsable<select value={editing.owner} onChange={e=>setEditing({...editing,owner:e.target.value})}>{owners.map(o=><option key={o}>{o}</option>)}</select></label>}</div>
 {editing.kind==='event'&&<label>Responsable<select value={editing.owner} onChange={e=>setEditing({...editing,owner:e.target.value})}>{owners.map(o=><option key={o}>{o}</option>)}</select></label>}
 {editing.kind!=='meal'?<><div className="mc-form-row"><label>Hora <small>(opcional)</small><input type="time" value={editing.time||''} onChange={e=>setEditing({...editing,time:e.target.value})}/></label><label>Tipo<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><div className="mc-form-row"><label>Repetir<select value={editing.recurrence} onChange={e=>setEditing({...editing,recurrence:e.target.value as any})}><option value="none">No se repite</option><option value="daily">Cada día</option><option value="weekdays">De lunes a viernes</option><option value="weekly">Cada semana</option><option value="yearly">Cada año</option></select></label><label>Preparar con antelación<select value={editing.reminderDays} onChange={e=>setEditing({...editing,reminderDays:Number(e.target.value)})}>{[0,1,3,7,14,30,60,90].map(n=><option key={n} value={n}>{n===0?'El mismo día':`${n} días antes`}</option>)}</select></label></div></>:<div className="mc-form-row"><label>Para quién<select value={editing.audience} onChange={e=>setEditing({...editing,audience:e.target.value as any})}><option value="adults">Los mayores</option><option value="kids">Las peques</option></select></label><label>Momento<select value={editing.slot} onChange={e=>setEditing({...editing,slot:e.target.value as any})}><option value="lunch">Comida</option><option value="dinner">Cena</option></select></label></div>}
 <label>{editing.kind==='meal'?'Ingredientes y preparación':'Detalles'}<textarea rows={3} value={editing.notes} maxLength={5000} onChange={e=>setEditing({...editing,notes:e.target.value})} placeholder={editing.kind==='meal'?'Ingredientes, cantidades, quién lo prepara…':'Lo que hace falta saber, sin tener que preguntar.'}/></label>
 {editing.kind==='task'&&<><label>Estado<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as any,completionDecision:undefined})}><option value="open">Pendiente</option><option value="done">Hecha</option><option value="cancelled">Cancelada / archivada</option></select></label></>}
 <label className="mc-checkbox-label"><Checkbox checked={editing.confirmed} onCheckedChange={v=>setEditing({...editing,confirmed:!!v})}/>Confirmado con la familia</label><p className="mc-source">{recordSource(editing)}</p></fieldset>
 {error&&<p role="alert" className="mc-error">{error}</p>}<div className="mc-form-actions">{editing.id&&!editing.readOnly&&(confirmDelete?<button type="button" className="mc-danger" onClick={()=>void remove()} disabled={busy}>Sí, eliminar</button>:<button type="button" className="mc-delete" onClick={()=>setConfirmDelete(true)}><Trash2 size={17}/> Eliminar</button>)}<Button type="button" variant="outline" onClick={()=>setEditing(null)}>Cerrar</Button>{!editing.readOnly&&<Button className="mc-primary" disabled={busy} type="submit">{busy?'Guardando…':'Guardar'}</Button>}</div></form>}</DialogContent></Dialog>
 </div>;
}
