import {NextRequest,NextResponse} from 'next/server';
import {verifiedFamilyEmail} from '@/lib/cloudflare-family-access';
import {requireCalendarSyncRouteAuth} from '@/lib/calendar-sync-auth';
import {createCapability,deleteCapability,listCapabilities,updateCapability,type CapabilityStatus} from '@/lib/family-mission/capability-store';
export const dynamic='force-dynamic';
const auth=async(req:NextRequest)=>{const email=await verifiedFamilyEmail(req.headers.get('cf-access-jwt-assertion'));if(email)return email;const service=await requireCalendarSyncRouteAuth(req);return service.authorized&&service.kind==='service'?'Rufus':null;};
const person=(email:string)=>email==='Rufus'?'Rufus':email.includes('cris')||email.includes('lacorte')?'Cris':'Dani';
export async function GET(req:NextRequest){if(!await auth(req))return NextResponse.json({error:'Unauthorized'},{status:401});try{return NextResponse.json({items:await listCapabilities()},{headers:{'Cache-Control':'private, no-store'}});}catch{return NextResponse.json({error:'No se pudo cargar el backlog.'},{status:503});}}
export async function POST(req:NextRequest){const email=await auth(req);if(!email)return NextResponse.json({error:'Unauthorized'},{status:401});try{const body=await req.json(),title=typeof body.title==='string'?body.title.trim().slice(0,200):'',notes=typeof body.notes==='string'?body.notes.trim().slice(0,2000):'';if(!title)return NextResponse.json({error:'Añade un título.'},{status:400});return NextResponse.json({item:await createCapability({title,notes,createdBy:person(email)})},{status:201});}catch{return NextResponse.json({error:'No se pudo guardar.'},{status:400});}}
export async function PATCH(req:NextRequest){if(!await auth(req))return NextResponse.json({error:'Unauthorized'},{status:401});try{const body=await req.json(),allowed:CapabilityStatus[]=['idea','planned','in_progress','done'];if(typeof body.id!=='string'||!allowed.includes(body.status))return NextResponse.json({error:'Datos no válidos.'},{status:400});return NextResponse.json({item:await updateCapability(body.id,body.status)});}catch{return NextResponse.json({error:'No se pudo actualizar.'},{status:404});}}
export async function DELETE(req:NextRequest){if(!await auth(req))return NextResponse.json({error:'Unauthorized'},{status:401});try{const body=await req.json();if(typeof body.id!=='string')return NextResponse.json({error:'Datos no válidos.'},{status:400});await deleteCapability(body.id);return NextResponse.json({ok:true});}catch{return NextResponse.json({error:'No se pudo eliminar.'},{status:404});}}
