import 'server-only';
import {getCloudflareContext} from '@opennextjs/cloudflare';
import type {Place,LocationLink,Person} from './location-model';
async function database(){const {env}=await getCloudflareContext({async:true});const db=(env as any).FAMILY_DB;if(!db)throw new Error('UNAVAILABLE');return db;}
const unpack=(row:any)=>({...JSON.parse(row.data),id:row.id,revision:row.revision});
export async function listLocations(person:Person|null){const db=await database();const read=async(table:string)=>{const r=await db.prepare(`SELECT * FROM ${table}${person?' WHERE person=?':''} ORDER BY id LIMIT 501`).bind(...(person?[person]:[])).all();if(r.results.length>500)throw new Error('LIMIT');return r.results.map(unpack);};const a=await db.prepare(`SELECT a.* FROM family_location_attention a JOIN family_location_links l ON l.id=a.rule_id JOIN family_places p ON p.id=l.place_id WHERE a.rule_revision=l.revision AND a.place_revision=p.revision AND json_extract(l.data,'$.enabled')=1${person?' AND a.person=?':''} LIMIT 500`).bind(...(person?[person]:[])).all();return {places:await read('family_places') as Place[],links:await read('family_location_links') as LocationLink[],attention:a.results.map((r:any)=>({ruleId:r.rule_id,state:r.state,observedAt:r.observed_at,validUntil:r.valid_until}))};}
export async function writeLocation(kind:'place'|'link',person:Person,data:any,id?:string,revision?:number){
 const db=await database(),table=kind==='place'?'family_places':'family_location_links';
 if(kind==='link'){const place=await db.prepare('SELECT person FROM family_places WHERE id=?').bind(data.placeId).first();if(place?.person!==person)throw new Error('INVALID');}
 const item={...data,person,id:id||crypto.randomUUID(),revision:id?Number(revision)+1:1};
 let result;
 if(id){result=await db.prepare(`UPDATE ${table} SET data=?,revision=revision+1${kind==='link'?',place_id=?,target_key=?':''} WHERE id=? AND person=? AND revision=?`).bind(JSON.stringify(item),...(kind==='link'?[item.placeId,JSON.stringify(item.target)]:[]),id,person,revision).run();}
 else{result=await db.prepare(`INSERT INTO ${table}(id,person,data${kind==='link'?',place_id,target_key':''}) VALUES(?,?,?${kind==='link'?',?,?':''})`).bind(item.id,person,JSON.stringify(item),...(kind==='link'?[item.placeId,JSON.stringify(item.target)]:[])).run();}
 if(!result.meta?.changes)throw new Error('CONFLICT');return item;
}
export async function deleteLocation(kind:'place'|'link',person:Person,id:string,revision:number){const db=await database();const table=kind==='place'?'family_places':'family_location_links';if(!(await db.prepare(`SELECT id FROM ${table} WHERE id=? AND person=? AND revision=?`).bind(id,person,revision).first()))throw new Error('CONFLICT');if(kind==='place'&&(await db.prepare('SELECT id FROM family_location_links WHERE place_id=? LIMIT 1').bind(id).first()))throw new Error('IN_USE');const r=await db.prepare(`DELETE FROM ${table} WHERE id=? AND person=? AND revision=?`).bind(id,person,revision).run();if(!r.meta?.changes)throw new Error('CONFLICT');}

export async function saveAttention(items:any[]){const db=await database();for(const item of items){const r=await db.prepare('SELECT * FROM family_location_links WHERE id=? AND person=?').bind(item.ruleId,item.person).first();if(!r||r.revision!==item.ruleRevision||!JSON.parse(r.data).enabled||!JSON.parse(r.data).confirmedAt)continue;const p=await db.prepare('SELECT revision FROM family_places WHERE id=? AND person=?').bind(r.place_id,item.person).first();if(p?.revision!==item.placeRevision)continue;await db.prepare(`INSERT INTO family_location_attention(rule_id,person,rule_revision,place_revision,state,observed_at,valid_until) VALUES(?,?,?,?,?,?,?) ON CONFLICT(rule_id) DO UPDATE SET rule_revision=excluded.rule_revision,place_revision=excluded.place_revision,state=excluded.state,observed_at=excluded.observed_at,valid_until=excluded.valid_until WHERE excluded.observed_at>family_location_attention.observed_at`).bind(item.ruleId,item.person,item.ruleRevision,item.placeRevision,item.state,item.observedAt,item.validUntil).run();}}
